#!/usr/bin/env python3

import argparse
import os
from subprocess import call
import sys

parser = argparse.ArgumentParser(prog='./dev')
subparsers = parser.add_subparsers(metavar='<command>', title='commands')

DOCKER_RUN = ['docker', 'run', '--init', '-it', '--rm', '-v',
              os.getcwd() + ':/src:cached', '-w=/src', 'node:10.8.0-alpine']

def start(args, remaining):
    call(DOCKER_RUN + ['yarn', 'install'])
parser_start = subparsers.add_parser('start',
    help='initialize the development environment')
parser_start.set_defaults(func=start)

def format(args, remaining):
    call(DOCKER_RUN + ['yarn', 'run', 'format'])
parser_format = subparsers.add_parser('format', help='format the code')
parser_format.set_defaults(func=format)

def lint(args, remaining):
    call(DOCKER_RUN + ['yarn', 'run', 'lint'])
parser_lint = subparsers.add_parser('lint', help='lint the code')
parser_lint.set_defaults(func=lint)

def sh(args, remaining):
    call(DOCKER_RUN + ['sh'])
parser_sh = subparsers.add_parser('sh', help='bring up a shell')
parser_sh.set_defaults(func=sh)

def yarn(args, remaining):
    call(DOCKER_RUN + ['yarn'] + remaining or [])
parser_yarn = subparsers.add_parser('yarn', help='run a yarn command')
parser_yarn.set_defaults(func=yarn)

def generate(args, remaining):
    call(DOCKER_RUN + ['yarn', 'run',
                       'generate' + (':watch' if args.watch else '')])
parser_generate = subparsers.add_parser('generate', help='generate the themes')
parser_generate.add_argument('-w', '--watch', action='store_true',
                             help='watch for file changes, and regenerate')
parser_generate.set_defaults(func=generate)

if len(sys.argv) > 1:
    args, remaining = parser.parse_known_args()
    args.func(args, remaining)
else:
    parser.print_help()
